SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR armv8-a)

SET(TOOLCHAIN_PREFIX aarch64-linux-gnu)

SET(CMAKE_C_COMPILER "/usr/bin/${TOOLCHAIN_PREFIX}-gcc-7")
SET(CMAKE_CXX_COMPILER "/usr/bin/${TOOLCHAIN_PREFIX}-g++-7")

SET(CMAKE_FIND_ROOT_PATH "/usr/${TOOLCHAIN_PREFIX}")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CFE_SYSTEM_PSPNAME "pc-linux")
SET(OSAL_SYSTEM_BSPTYPE "generic-linux")
SET(OSAL_SYSTEM_OSTYPE "posix")
